<?php

namespace FancyFlux;

class EmojiData
{
    /**
     * Get all emoji categories with their emojis.
     *
     * @return array<string, array{icon: string, label: string, emojis: array<array{char: string, name: string}>}>
     */
    public static function categories(): array
    {
        return [
            'smileys' => [
                'icon' => '😀',
                'label' => 'Smileys',
                'emojis' => self::smileys(),
            ],
            'people' => [
                'icon' => '👋',
                'label' => 'People',
                'emojis' => self::people(),
            ],
            'animals' => [
                'icon' => '🐱',
                'label' => 'Animals',
                'emojis' => self::animals(),
            ],
            'food' => [
                'icon' => '🍔',
                'label' => 'Food',
                'emojis' => self::food(),
            ],
            'activities' => [
                'icon' => '⚽',
                'label' => 'Activities',
                'emojis' => self::activities(),
            ],
            'travel' => [
                'icon' => '🚗',
                'label' => 'Travel',
                'emojis' => self::travel(),
            ],
            'symbols' => [
                'icon' => '❤️',
                'label' => 'Symbols',
                'emojis' => self::symbols(),
            ],
            'flags' => [
                'icon' => '🏳️',
                'label' => 'Flags',
                'emojis' => self::flags(),
            ],
        ];
    }

    /**
     * Get flat list of all emojis for searching.
     *
     * @return array<array{char: string, name: string, category: string}>
     */
    public static function all(): array
    {
        $all = [];
        foreach (self::categories() as $key => $category) {
            foreach ($category['emojis'] as $emoji) {
                $all[] = array_merge($emoji, ['category' => $key]);
            }
        }
        return $all;
    }

    protected static function smileys(): array
    {
        return [
            ['char' => '😀', 'name' => 'grinning face'],
            ['char' => '😃', 'name' => 'grinning face with big eyes'],
            ['char' => '😄', 'name' => 'grinning face with smiling eyes'],
            ['char' => '😁', 'name' => 'beaming face with smiling eyes'],
            ['char' => '😆', 'name' => 'grinning squinting face'],
            ['char' => '😅', 'name' => 'grinning face with sweat'],
            ['char' => '🤣', 'name' => 'rolling on the floor laughing'],
            ['char' => '😂', 'name' => 'face with tears of joy'],
            ['char' => '🙂', 'name' => 'slightly smiling face'],
            ['char' => '🙃', 'name' => 'upside-down face'],
            ['char' => '😉', 'name' => 'winking face'],
            ['char' => '😊', 'name' => 'smiling face with smiling eyes'],
            ['char' => '😇', 'name' => 'smiling face with halo'],
            ['char' => '🥰', 'name' => 'smiling face with hearts'],
            ['char' => '😍', 'name' => 'smiling face with heart-eyes'],
            ['char' => '🤩', 'name' => 'star-struck'],
            ['char' => '😘', 'name' => 'face blowing a kiss'],
            ['char' => '😗', 'name' => 'kissing face'],
            ['char' => '😚', 'name' => 'kissing face with closed eyes'],
            ['char' => '😙', 'name' => 'kissing face with smiling eyes'],
            ['char' => '🥲', 'name' => 'smiling face with tear'],
            ['char' => '😋', 'name' => 'face savoring food'],
            ['char' => '😛', 'name' => 'face with tongue'],
            ['char' => '😜', 'name' => 'winking face with tongue'],
            ['char' => '🤪', 'name' => 'zany face'],
            ['char' => '😝', 'name' => 'squinting face with tongue'],
            ['char' => '🤑', 'name' => 'money-mouth face'],
            ['char' => '🤗', 'name' => 'hugging face'],
            ['char' => '🤭', 'name' => 'face with hand over mouth'],
            ['char' => '🤫', 'name' => 'shushing face'],
            ['char' => '🤔', 'name' => 'thinking face'],
            ['char' => '🤐', 'name' => 'zipper-mouth face'],
            ['char' => '🤨', 'name' => 'face with raised eyebrow'],
            ['char' => '😐', 'name' => 'neutral face'],
            ['char' => '😑', 'name' => 'expressionless face'],
            ['char' => '😶', 'name' => 'face without mouth'],
            ['char' => '😏', 'name' => 'smirking face'],
            ['char' => '😒', 'name' => 'unamused face'],
            ['char' => '🙄', 'name' => 'face with rolling eyes'],
            ['char' => '😬', 'name' => 'grimacing face'],
            ['char' => '🤥', 'name' => 'lying face'],
            ['char' => '😌', 'name' => 'relieved face'],
            ['char' => '😔', 'name' => 'pensive face'],
            ['char' => '😪', 'name' => 'sleepy face'],
            ['char' => '🤤', 'name' => 'drooling face'],
            ['char' => '😴', 'name' => 'sleeping face'],
            ['char' => '😷', 'name' => 'face with medical mask'],
            ['char' => '🤒', 'name' => 'face with thermometer'],
            ['char' => '🤕', 'name' => 'face with head-bandage'],
            ['char' => '🤢', 'name' => 'nauseated face'],
            ['char' => '🤮', 'name' => 'face vomiting'],
            ['char' => '🤧', 'name' => 'sneezing face'],
            ['char' => '🥵', 'name' => 'hot face'],
            ['char' => '🥶', 'name' => 'cold face'],
            ['char' => '🥴', 'name' => 'woozy face'],
            ['char' => '😵', 'name' => 'dizzy face'],
            ['char' => '🤯', 'name' => 'exploding head'],
            ['char' => '🤠', 'name' => 'cowboy hat face'],
            ['char' => '🥳', 'name' => 'partying face'],
            ['char' => '🥸', 'name' => 'disguised face'],
            ['char' => '😎', 'name' => 'smiling face with sunglasses'],
            ['char' => '🤓', 'name' => 'nerd face'],
            ['char' => '🧐', 'name' => 'face with monocle'],
            ['char' => '😕', 'name' => 'confused face'],
            ['char' => '😟', 'name' => 'worried face'],
            ['char' => '🙁', 'name' => 'slightly frowning face'],
            ['char' => '😮', 'name' => 'face with open mouth'],
            ['char' => '😯', 'name' => 'hushed face'],
            ['char' => '😲', 'name' => 'astonished face'],
            ['char' => '😳', 'name' => 'flushed face'],
            ['char' => '🥺', 'name' => 'pleading face'],
            ['char' => '😦', 'name' => 'frowning face with open mouth'],
            ['char' => '😧', 'name' => 'anguished face'],
            ['char' => '😨', 'name' => 'fearful face'],
            ['char' => '😰', 'name' => 'anxious face with sweat'],
            ['char' => '😥', 'name' => 'sad but relieved face'],
            ['char' => '😢', 'name' => 'crying face'],
            ['char' => '😭', 'name' => 'loudly crying face'],
            ['char' => '😱', 'name' => 'face screaming in fear'],
            ['char' => '😖', 'name' => 'confounded face'],
            ['char' => '😣', 'name' => 'persevering face'],
            ['char' => '😞', 'name' => 'disappointed face'],
            ['char' => '😓', 'name' => 'downcast face with sweat'],
            ['char' => '😩', 'name' => 'weary face'],
            ['char' => '😫', 'name' => 'tired face'],
            ['char' => '🥱', 'name' => 'yawning face'],
            ['char' => '😤', 'name' => 'face with steam from nose'],
            ['char' => '😡', 'name' => 'pouting face'],
            ['char' => '😠', 'name' => 'angry face'],
            ['char' => '🤬', 'name' => 'face with symbols on mouth'],
            ['char' => '😈', 'name' => 'smiling face with horns'],
            ['char' => '👿', 'name' => 'angry face with horns'],
            ['char' => '💀', 'name' => 'skull'],
            ['char' => '💩', 'name' => 'pile of poo'],
            ['char' => '🤡', 'name' => 'clown face'],
            ['char' => '👹', 'name' => 'ogre'],
            ['char' => '👺', 'name' => 'goblin'],
            ['char' => '👻', 'name' => 'ghost'],
            ['char' => '👽', 'name' => 'alien'],
            ['char' => '👾', 'name' => 'alien monster'],
            ['char' => '🤖', 'name' => 'robot'],
        ];
    }

    protected static function people(): array
    {
        return [
            ['char' => '👋', 'name' => 'waving hand'],
            ['char' => '🤚', 'name' => 'raised back of hand'],
            ['char' => '🖐', 'name' => 'hand with fingers splayed'],
            ['char' => '✋', 'name' => 'raised hand'],
            ['char' => '🖖', 'name' => 'vulcan salute'],
            ['char' => '👌', 'name' => 'ok hand'],
            ['char' => '🤌', 'name' => 'pinched fingers'],
            ['char' => '🤏', 'name' => 'pinching hand'],
            ['char' => '✌️', 'name' => 'victory hand'],
            ['char' => '🤞', 'name' => 'crossed fingers'],
            ['char' => '🤟', 'name' => 'love-you gesture'],
            ['char' => '🤘', 'name' => 'sign of the horns'],
            ['char' => '🤙', 'name' => 'call me hand'],
            ['char' => '👈', 'name' => 'backhand index pointing left'],
            ['char' => '👉', 'name' => 'backhand index pointing right'],
            ['char' => '👆', 'name' => 'backhand index pointing up'],
            ['char' => '👇', 'name' => 'backhand index pointing down'],
            ['char' => '☝️', 'name' => 'index pointing up'],
            ['char' => '👍', 'name' => 'thumbs up'],
            ['char' => '👎', 'name' => 'thumbs down'],
            ['char' => '✊', 'name' => 'raised fist'],
            ['char' => '👊', 'name' => 'oncoming fist'],
            ['char' => '🤛', 'name' => 'left-facing fist'],
            ['char' => '🤜', 'name' => 'right-facing fist'],
            ['char' => '👏', 'name' => 'clapping hands'],
            ['char' => '🙌', 'name' => 'raising hands'],
            ['char' => '👐', 'name' => 'open hands'],
            ['char' => '🤲', 'name' => 'palms up together'],
            ['char' => '🤝', 'name' => 'handshake'],
            ['char' => '🙏', 'name' => 'folded hands'],
            ['char' => '✍️', 'name' => 'writing hand'],
            ['char' => '💅', 'name' => 'nail polish'],
            ['char' => '🤳', 'name' => 'selfie'],
            ['char' => '💪', 'name' => 'flexed biceps'],
            ['char' => '👶', 'name' => 'baby'],
            ['char' => '👧', 'name' => 'girl'],
            ['char' => '🧒', 'name' => 'child'],
            ['char' => '👦', 'name' => 'boy'],
            ['char' => '👩', 'name' => 'woman'],
            ['char' => '🧑', 'name' => 'person'],
            ['char' => '👨', 'name' => 'man'],
            ['char' => '👵', 'name' => 'old woman'],
            ['char' => '🧓', 'name' => 'older person'],
            ['char' => '👴', 'name' => 'old man'],
            ['char' => '👮', 'name' => 'police officer'],
            ['char' => '👷', 'name' => 'construction worker'],
            ['char' => '💂', 'name' => 'guard'],
            ['char' => '🕵️', 'name' => 'detective'],
            ['char' => '👩‍⚕️', 'name' => 'woman health worker'],
            ['char' => '👨‍⚕️', 'name' => 'man health worker'],
            ['char' => '👩‍🎓', 'name' => 'woman student'],
            ['char' => '👨‍🎓', 'name' => 'man student'],
            ['char' => '👩‍💻', 'name' => 'woman technologist'],
            ['char' => '👨‍💻', 'name' => 'man technologist'],
            ['char' => '🧙', 'name' => 'mage'],
            ['char' => '🧚', 'name' => 'fairy'],
            ['char' => '🧛', 'name' => 'vampire'],
            ['char' => '🧜', 'name' => 'merperson'],
            ['char' => '🧝', 'name' => 'elf'],
            ['char' => '🧞', 'name' => 'genie'],
            ['char' => '🧟', 'name' => 'zombie'],
            ['char' => '💆', 'name' => 'person getting massage'],
            ['char' => '💇', 'name' => 'person getting haircut'],
            ['char' => '🚶', 'name' => 'person walking'],
            ['char' => '🧍', 'name' => 'person standing'],
            ['char' => '🧎', 'name' => 'person kneeling'],
            ['char' => '🏃', 'name' => 'person running'],
            ['char' => '💃', 'name' => 'woman dancing'],
            ['char' => '🕺', 'name' => 'man dancing'],
            ['char' => '👫', 'name' => 'woman and man holding hands'],
            ['char' => '👭', 'name' => 'women holding hands'],
            ['char' => '👬', 'name' => 'men holding hands'],
            ['char' => '💏', 'name' => 'kiss'],
            ['char' => '💑', 'name' => 'couple with heart'],
            ['char' => '👪', 'name' => 'family'],
        ];
    }

    protected static function animals(): array
    {
        return [
            ['char' => '🐶', 'name' => 'dog face'],
            ['char' => '🐱', 'name' => 'cat face'],
            ['char' => '🐭', 'name' => 'mouse face'],
            ['char' => '🐹', 'name' => 'hamster'],
            ['char' => '🐰', 'name' => 'rabbit face'],
            ['char' => '🦊', 'name' => 'fox'],
            ['char' => '🐻', 'name' => 'bear'],
            ['char' => '🐼', 'name' => 'panda'],
            ['char' => '🐨', 'name' => 'koala'],
            ['char' => '🐯', 'name' => 'tiger face'],
            ['char' => '🦁', 'name' => 'lion'],
            ['char' => '🐮', 'name' => 'cow face'],
            ['char' => '🐷', 'name' => 'pig face'],
            ['char' => '🐸', 'name' => 'frog'],
            ['char' => '🐵', 'name' => 'monkey face'],
            ['char' => '🙈', 'name' => 'see-no-evil monkey'],
            ['char' => '🙉', 'name' => 'hear-no-evil monkey'],
            ['char' => '🙊', 'name' => 'speak-no-evil monkey'],
            ['char' => '🐒', 'name' => 'monkey'],
            ['char' => '🐔', 'name' => 'chicken'],
            ['char' => '🐧', 'name' => 'penguin'],
            ['char' => '🐦', 'name' => 'bird'],
            ['char' => '🐤', 'name' => 'baby chick'],
            ['char' => '🦆', 'name' => 'duck'],
            ['char' => '🦅', 'name' => 'eagle'],
            ['char' => '🦉', 'name' => 'owl'],
            ['char' => '🦇', 'name' => 'bat'],
            ['char' => '🐺', 'name' => 'wolf'],
            ['char' => '🐗', 'name' => 'boar'],
            ['char' => '🐴', 'name' => 'horse face'],
            ['char' => '🦄', 'name' => 'unicorn'],
            ['char' => '🐝', 'name' => 'honeybee'],
            ['char' => '🐛', 'name' => 'bug'],
            ['char' => '🦋', 'name' => 'butterfly'],
            ['char' => '🐌', 'name' => 'snail'],
            ['char' => '🐞', 'name' => 'lady beetle'],
            ['char' => '🐜', 'name' => 'ant'],
            ['char' => '🦟', 'name' => 'mosquito'],
            ['char' => '🐢', 'name' => 'turtle'],
            ['char' => '🐍', 'name' => 'snake'],
            ['char' => '🦎', 'name' => 'lizard'],
            ['char' => '🐙', 'name' => 'octopus'],
            ['char' => '🦑', 'name' => 'squid'],
            ['char' => '🦐', 'name' => 'shrimp'],
            ['char' => '🦀', 'name' => 'crab'],
            ['char' => '🐡', 'name' => 'blowfish'],
            ['char' => '🐠', 'name' => 'tropical fish'],
            ['char' => '🐟', 'name' => 'fish'],
            ['char' => '🐬', 'name' => 'dolphin'],
            ['char' => '🐳', 'name' => 'spouting whale'],
            ['char' => '🐋', 'name' => 'whale'],
            ['char' => '🦈', 'name' => 'shark'],
            ['char' => '🐊', 'name' => 'crocodile'],
            ['char' => '🐅', 'name' => 'tiger'],
            ['char' => '🐆', 'name' => 'leopard'],
            ['char' => '🦓', 'name' => 'zebra'],
            ['char' => '🦍', 'name' => 'gorilla'],
            ['char' => '🦧', 'name' => 'orangutan'],
            ['char' => '🐘', 'name' => 'elephant'],
            ['char' => '🦛', 'name' => 'hippopotamus'],
            ['char' => '🦏', 'name' => 'rhinoceros'],
            ['char' => '🐪', 'name' => 'camel'],
            ['char' => '🐫', 'name' => 'two-hump camel'],
            ['char' => '🦒', 'name' => 'giraffe'],
            ['char' => '🦘', 'name' => 'kangaroo'],
            ['char' => '🐃', 'name' => 'water buffalo'],
            ['char' => '🐂', 'name' => 'ox'],
            ['char' => '🐄', 'name' => 'cow'],
            ['char' => '🐎', 'name' => 'horse'],
            ['char' => '🐖', 'name' => 'pig'],
            ['char' => '🐏', 'name' => 'ram'],
            ['char' => '🐑', 'name' => 'ewe'],
            ['char' => '🦙', 'name' => 'llama'],
            ['char' => '🐐', 'name' => 'goat'],
            ['char' => '🦌', 'name' => 'deer'],
            ['char' => '🐕', 'name' => 'dog'],
            ['char' => '🐩', 'name' => 'poodle'],
            ['char' => '🦮', 'name' => 'guide dog'],
            ['char' => '🐈', 'name' => 'cat'],
            ['char' => '🐓', 'name' => 'rooster'],
            ['char' => '🦃', 'name' => 'turkey'],
            ['char' => '🦚', 'name' => 'peacock'],
            ['char' => '🦜', 'name' => 'parrot'],
            ['char' => '🦢', 'name' => 'swan'],
            ['char' => '🦩', 'name' => 'flamingo'],
            ['char' => '🐇', 'name' => 'rabbit'],
            ['char' => '🦝', 'name' => 'raccoon'],
            ['char' => '🦨', 'name' => 'skunk'],
            ['char' => '🦡', 'name' => 'badger'],
            ['char' => '🦫', 'name' => 'beaver'],
            ['char' => '🦦', 'name' => 'otter'],
            ['char' => '🦥', 'name' => 'sloth'],
        ];
    }

    protected static function food(): array
    {
        return [
            ['char' => '🍏', 'name' => 'green apple'],
            ['char' => '🍎', 'name' => 'red apple'],
            ['char' => '🍐', 'name' => 'pear'],
            ['char' => '🍊', 'name' => 'tangerine'],
            ['char' => '🍋', 'name' => 'lemon'],
            ['char' => '🍌', 'name' => 'banana'],
            ['char' => '🍉', 'name' => 'watermelon'],
            ['char' => '🍇', 'name' => 'grapes'],
            ['char' => '🍓', 'name' => 'strawberry'],
            ['char' => '🫐', 'name' => 'blueberries'],
            ['char' => '🍈', 'name' => 'melon'],
            ['char' => '🍒', 'name' => 'cherries'],
            ['char' => '🍑', 'name' => 'peach'],
            ['char' => '🥭', 'name' => 'mango'],
            ['char' => '🍍', 'name' => 'pineapple'],
            ['char' => '🥥', 'name' => 'coconut'],
            ['char' => '🥝', 'name' => 'kiwi fruit'],
            ['char' => '🍅', 'name' => 'tomato'],
            ['char' => '🍆', 'name' => 'eggplant'],
            ['char' => '🥑', 'name' => 'avocado'],
            ['char' => '🥦', 'name' => 'broccoli'],
            ['char' => '🥬', 'name' => 'leafy green'],
            ['char' => '🥒', 'name' => 'cucumber'],
            ['char' => '🌶️', 'name' => 'hot pepper'],
            ['char' => '🫑', 'name' => 'bell pepper'],
            ['char' => '🌽', 'name' => 'ear of corn'],
            ['char' => '🥕', 'name' => 'carrot'],
            ['char' => '🧄', 'name' => 'garlic'],
            ['char' => '🧅', 'name' => 'onion'],
            ['char' => '🥔', 'name' => 'potato'],
            ['char' => '🍠', 'name' => 'roasted sweet potato'],
            ['char' => '🥐', 'name' => 'croissant'],
            ['char' => '🥯', 'name' => 'bagel'],
            ['char' => '🍞', 'name' => 'bread'],
            ['char' => '🥖', 'name' => 'baguette bread'],
            ['char' => '🥨', 'name' => 'pretzel'],
            ['char' => '🧀', 'name' => 'cheese wedge'],
            ['char' => '🥚', 'name' => 'egg'],
            ['char' => '🍳', 'name' => 'cooking'],
            ['char' => '🧈', 'name' => 'butter'],
            ['char' => '🥞', 'name' => 'pancakes'],
            ['char' => '🧇', 'name' => 'waffle'],
            ['char' => '🥓', 'name' => 'bacon'],
            ['char' => '🥩', 'name' => 'cut of meat'],
            ['char' => '🍗', 'name' => 'poultry leg'],
            ['char' => '🍖', 'name' => 'meat on bone'],
            ['char' => '🌭', 'name' => 'hot dog'],
            ['char' => '🍔', 'name' => 'hamburger'],
            ['char' => '🍟', 'name' => 'french fries'],
            ['char' => '🍕', 'name' => 'pizza'],
            ['char' => '🥪', 'name' => 'sandwich'],
            ['char' => '🥙', 'name' => 'stuffed flatbread'],
            ['char' => '🧆', 'name' => 'falafel'],
            ['char' => '🌮', 'name' => 'taco'],
            ['char' => '🌯', 'name' => 'burrito'],
            ['char' => '🥗', 'name' => 'green salad'],
            ['char' => '🥘', 'name' => 'shallow pan of food'],
            ['char' => '🍝', 'name' => 'spaghetti'],
            ['char' => '🍜', 'name' => 'steaming bowl'],
            ['char' => '🍲', 'name' => 'pot of food'],
            ['char' => '🍛', 'name' => 'curry rice'],
            ['char' => '🍣', 'name' => 'sushi'],
            ['char' => '🍱', 'name' => 'bento box'],
            ['char' => '🥟', 'name' => 'dumpling'],
            ['char' => '🍤', 'name' => 'fried shrimp'],
            ['char' => '🍙', 'name' => 'rice ball'],
            ['char' => '🍚', 'name' => 'cooked rice'],
            ['char' => '🍘', 'name' => 'rice cracker'],
            ['char' => '🍥', 'name' => 'fish cake with swirl'],
            ['char' => '🥮', 'name' => 'moon cake'],
            ['char' => '🍢', 'name' => 'oden'],
            ['char' => '🍡', 'name' => 'dango'],
            ['char' => '🍧', 'name' => 'shaved ice'],
            ['char' => '🍨', 'name' => 'ice cream'],
            ['char' => '🍦', 'name' => 'soft ice cream'],
            ['char' => '🥧', 'name' => 'pie'],
            ['char' => '🧁', 'name' => 'cupcake'],
            ['char' => '🍰', 'name' => 'shortcake'],
            ['char' => '🎂', 'name' => 'birthday cake'],
            ['char' => '🍮', 'name' => 'custard'],
            ['char' => '🍭', 'name' => 'lollipop'],
            ['char' => '🍬', 'name' => 'candy'],
            ['char' => '🍫', 'name' => 'chocolate bar'],
            ['char' => '🍿', 'name' => 'popcorn'],
            ['char' => '🍩', 'name' => 'doughnut'],
            ['char' => '🍪', 'name' => 'cookie'],
            ['char' => '🌰', 'name' => 'chestnut'],
            ['char' => '🥜', 'name' => 'peanuts'],
            ['char' => '🍯', 'name' => 'honey pot'],
            ['char' => '☕', 'name' => 'hot beverage'],
            ['char' => '🍵', 'name' => 'teacup without handle'],
            ['char' => '🧃', 'name' => 'beverage box'],
            ['char' => '🥤', 'name' => 'cup with straw'],
            ['char' => '🧋', 'name' => 'bubble tea'],
            ['char' => '🍶', 'name' => 'sake'],
            ['char' => '🍺', 'name' => 'beer mug'],
            ['char' => '🍻', 'name' => 'clinking beer mugs'],
            ['char' => '🥂', 'name' => 'clinking glasses'],
            ['char' => '🍷', 'name' => 'wine glass'],
            ['char' => '🥃', 'name' => 'tumbler glass'],
            ['char' => '🍸', 'name' => 'cocktail glass'],
            ['char' => '🍹', 'name' => 'tropical drink'],
            ['char' => '🧊', 'name' => 'ice'],
        ];
    }

    protected static function activities(): array
    {
        return [
            ['char' => '⚽', 'name' => 'soccer ball'],
            ['char' => '🏀', 'name' => 'basketball'],
            ['char' => '🏈', 'name' => 'american football'],
            ['char' => '⚾', 'name' => 'baseball'],
            ['char' => '🥎', 'name' => 'softball'],
            ['char' => '🎾', 'name' => 'tennis'],
            ['char' => '🏐', 'name' => 'volleyball'],
            ['char' => '🏉', 'name' => 'rugby football'],
            ['char' => '🥏', 'name' => 'flying disc'],
            ['char' => '🎱', 'name' => 'pool 8 ball'],
            ['char' => '🪀', 'name' => 'yo-yo'],
            ['char' => '🏓', 'name' => 'ping pong'],
            ['char' => '🏸', 'name' => 'badminton'],
            ['char' => '🏒', 'name' => 'ice hockey'],
            ['char' => '🏑', 'name' => 'field hockey'],
            ['char' => '🥍', 'name' => 'lacrosse'],
            ['char' => '🏏', 'name' => 'cricket game'],
            ['char' => '🪃', 'name' => 'boomerang'],
            ['char' => '🥅', 'name' => 'goal net'],
            ['char' => '⛳', 'name' => 'flag in hole'],
            ['char' => '🪁', 'name' => 'kite'],
            ['char' => '🏹', 'name' => 'bow and arrow'],
            ['char' => '🎣', 'name' => 'fishing pole'],
            ['char' => '🤿', 'name' => 'diving mask'],
            ['char' => '🥊', 'name' => 'boxing glove'],
            ['char' => '🥋', 'name' => 'martial arts uniform'],
            ['char' => '🎽', 'name' => 'running shirt'],
            ['char' => '🛹', 'name' => 'skateboard'],
            ['char' => '🛼', 'name' => 'roller skate'],
            ['char' => '🛷', 'name' => 'sled'],
            ['char' => '⛸️', 'name' => 'ice skate'],
            ['char' => '🥌', 'name' => 'curling stone'],
            ['char' => '🎿', 'name' => 'skis'],
            ['char' => '⛷️', 'name' => 'skier'],
            ['char' => '🏂', 'name' => 'snowboarder'],
            ['char' => '🏋️', 'name' => 'person lifting weights'],
            ['char' => '🤼', 'name' => 'people wrestling'],
            ['char' => '🤸', 'name' => 'person cartwheeling'],
            ['char' => '🤺', 'name' => 'person fencing'],
            ['char' => '⛹️', 'name' => 'person bouncing ball'],
            ['char' => '🤾', 'name' => 'person playing handball'],
            ['char' => '🏌️', 'name' => 'person golfing'],
            ['char' => '🏇', 'name' => 'horse racing'],
            ['char' => '🧘', 'name' => 'person in lotus position'],
            ['char' => '🏄', 'name' => 'person surfing'],
            ['char' => '🏊', 'name' => 'person swimming'],
            ['char' => '🤽', 'name' => 'person playing water polo'],
            ['char' => '🚣', 'name' => 'person rowing boat'],
            ['char' => '🧗', 'name' => 'person climbing'],
            ['char' => '🚴', 'name' => 'person biking'],
            ['char' => '🚵', 'name' => 'person mountain biking'],
            ['char' => '🎪', 'name' => 'circus tent'],
            ['char' => '🎭', 'name' => 'performing arts'],
            ['char' => '🎨', 'name' => 'artist palette'],
            ['char' => '🎬', 'name' => 'clapper board'],
            ['char' => '🎤', 'name' => 'microphone'],
            ['char' => '🎧', 'name' => 'headphone'],
            ['char' => '🎼', 'name' => 'musical score'],
            ['char' => '🎹', 'name' => 'musical keyboard'],
            ['char' => '🥁', 'name' => 'drum'],
            ['char' => '🎷', 'name' => 'saxophone'],
            ['char' => '🎺', 'name' => 'trumpet'],
            ['char' => '🎸', 'name' => 'guitar'],
            ['char' => '🪕', 'name' => 'banjo'],
            ['char' => '🎻', 'name' => 'violin'],
            ['char' => '🎲', 'name' => 'game die'],
            ['char' => '♟️', 'name' => 'chess pawn'],
            ['char' => '🎯', 'name' => 'direct hit'],
            ['char' => '🎳', 'name' => 'bowling'],
            ['char' => '🎮', 'name' => 'video game'],
            ['char' => '🎰', 'name' => 'slot machine'],
            ['char' => '🧩', 'name' => 'puzzle piece'],
            ['char' => '🏆', 'name' => 'trophy'],
            ['char' => '🏅', 'name' => 'sports medal'],
            ['char' => '🥇', 'name' => 'first place medal'],
            ['char' => '🥈', 'name' => 'second place medal'],
            ['char' => '🥉', 'name' => 'third place medal'],
        ];
    }

    protected static function travel(): array
    {
        return [
            ['char' => '🚗', 'name' => 'automobile'],
            ['char' => '🚕', 'name' => 'taxi'],
            ['char' => '🚙', 'name' => 'sport utility vehicle'],
            ['char' => '🚌', 'name' => 'bus'],
            ['char' => '🚎', 'name' => 'trolleybus'],
            ['char' => '🏎️', 'name' => 'racing car'],
            ['char' => '🚓', 'name' => 'police car'],
            ['char' => '🚑', 'name' => 'ambulance'],
            ['char' => '🚒', 'name' => 'fire engine'],
            ['char' => '🚐', 'name' => 'minibus'],
            ['char' => '🛻', 'name' => 'pickup truck'],
            ['char' => '🚚', 'name' => 'delivery truck'],
            ['char' => '🚛', 'name' => 'articulated lorry'],
            ['char' => '🚜', 'name' => 'tractor'],
            ['char' => '🏍️', 'name' => 'motorcycle'],
            ['char' => '🛵', 'name' => 'motor scooter'],
            ['char' => '🚲', 'name' => 'bicycle'],
            ['char' => '🛴', 'name' => 'kick scooter'],
            ['char' => '🚨', 'name' => 'police car light'],
            ['char' => '🚔', 'name' => 'oncoming police car'],
            ['char' => '🚍', 'name' => 'oncoming bus'],
            ['char' => '🚘', 'name' => 'oncoming automobile'],
            ['char' => '🚖', 'name' => 'oncoming taxi'],
            ['char' => '🚃', 'name' => 'railway car'],
            ['char' => '🚋', 'name' => 'tram car'],
            ['char' => '🚞', 'name' => 'mountain railway'],
            ['char' => '🚝', 'name' => 'monorail'],
            ['char' => '🚄', 'name' => 'high-speed train'],
            ['char' => '🚅', 'name' => 'bullet train'],
            ['char' => '🚈', 'name' => 'light rail'],
            ['char' => '🚂', 'name' => 'locomotive'],
            ['char' => '🚆', 'name' => 'train'],
            ['char' => '🚇', 'name' => 'metro'],
            ['char' => '🚊', 'name' => 'tram'],
            ['char' => '🚉', 'name' => 'station'],
            ['char' => '✈️', 'name' => 'airplane'],
            ['char' => '🛫', 'name' => 'airplane departure'],
            ['char' => '🛬', 'name' => 'airplane arrival'],
            ['char' => '🛩️', 'name' => 'small airplane'],
            ['char' => '🚀', 'name' => 'rocket'],
            ['char' => '🛸', 'name' => 'flying saucer'],
            ['char' => '🚁', 'name' => 'helicopter'],
            ['char' => '🛶', 'name' => 'canoe'],
            ['char' => '⛵', 'name' => 'sailboat'],
            ['char' => '🚤', 'name' => 'speedboat'],
            ['char' => '🛥️', 'name' => 'motor boat'],
            ['char' => '🛳️', 'name' => 'passenger ship'],
            ['char' => '⛴️', 'name' => 'ferry'],
            ['char' => '🚢', 'name' => 'ship'],
            ['char' => '⚓', 'name' => 'anchor'],
            ['char' => '⛽', 'name' => 'fuel pump'],
            ['char' => '🚧', 'name' => 'construction'],
            ['char' => '🚦', 'name' => 'vertical traffic light'],
            ['char' => '🚥', 'name' => 'horizontal traffic light'],
            ['char' => '🚏', 'name' => 'bus stop'],
            ['char' => '🗺️', 'name' => 'world map'],
            ['char' => '🗿', 'name' => 'moai'],
            ['char' => '🗽', 'name' => 'Statue of Liberty'],
            ['char' => '🗼', 'name' => 'Tokyo tower'],
            ['char' => '🏰', 'name' => 'castle'],
            ['char' => '🏯', 'name' => 'Japanese castle'],
            ['char' => '🏟️', 'name' => 'stadium'],
            ['char' => '🎡', 'name' => 'ferris wheel'],
            ['char' => '🎢', 'name' => 'roller coaster'],
            ['char' => '🎠', 'name' => 'carousel horse'],
            ['char' => '⛲', 'name' => 'fountain'],
            ['char' => '⛱️', 'name' => 'umbrella on ground'],
            ['char' => '🏖️', 'name' => 'beach with umbrella'],
            ['char' => '🏝️', 'name' => 'desert island'],
            ['char' => '🏜️', 'name' => 'desert'],
            ['char' => '🌋', 'name' => 'volcano'],
            ['char' => '⛰️', 'name' => 'mountain'],
            ['char' => '🏔️', 'name' => 'snow-capped mountain'],
            ['char' => '🗻', 'name' => 'mount fuji'],
            ['char' => '🏕️', 'name' => 'camping'],
            ['char' => '⛺', 'name' => 'tent'],
            ['char' => '🏠', 'name' => 'house'],
            ['char' => '🏡', 'name' => 'house with garden'],
            ['char' => '🏢', 'name' => 'office building'],
            ['char' => '🏣', 'name' => 'Japanese post office'],
            ['char' => '🏤', 'name' => 'post office'],
            ['char' => '🏥', 'name' => 'hospital'],
            ['char' => '🏦', 'name' => 'bank'],
            ['char' => '🏨', 'name' => 'hotel'],
            ['char' => '🏩', 'name' => 'love hotel'],
            ['char' => '🏪', 'name' => 'convenience store'],
            ['char' => '🏫', 'name' => 'school'],
            ['char' => '🏬', 'name' => 'department store'],
            ['char' => '🏭', 'name' => 'factory'],
            ['char' => '🏗️', 'name' => 'building construction'],
            ['char' => '🧱', 'name' => 'brick'],
            ['char' => '🌅', 'name' => 'sunrise'],
            ['char' => '🌄', 'name' => 'sunrise over mountains'],
            ['char' => '🌠', 'name' => 'shooting star'],
            ['char' => '🎇', 'name' => 'sparkler'],
            ['char' => '🎆', 'name' => 'fireworks'],
            ['char' => '🌇', 'name' => 'sunset'],
            ['char' => '🌆', 'name' => 'cityscape at dusk'],
            ['char' => '🏙️', 'name' => 'cityscape'],
            ['char' => '🌃', 'name' => 'night with stars'],
            ['char' => '🌌', 'name' => 'milky way'],
            ['char' => '🌉', 'name' => 'bridge at night'],
            ['char' => '🌁', 'name' => 'foggy'],
        ];
    }

    protected static function objects(): array
    {
        return [
            ['char' => '⌚', 'name' => 'watch'],
            ['char' => '📱', 'name' => 'mobile phone'],
            ['char' => '📲', 'name' => 'mobile phone with arrow'],
            ['char' => '💻', 'name' => 'laptop'],
            ['char' => '⌨️', 'name' => 'keyboard'],
            ['char' => '🖥️', 'name' => 'desktop computer'],
            ['char' => '🖨️', 'name' => 'printer'],
            ['char' => '🖱️', 'name' => 'computer mouse'],
            ['char' => '💽', 'name' => 'computer disk'],
            ['char' => '💾', 'name' => 'floppy disk'],
            ['char' => '💿', 'name' => 'optical disk'],
            ['char' => '📀', 'name' => 'dvd'],
            ['char' => '📼', 'name' => 'videocassette'],
            ['char' => '📷', 'name' => 'camera'],
            ['char' => '📸', 'name' => 'camera with flash'],
            ['char' => '📹', 'name' => 'video camera'],
            ['char' => '🎥', 'name' => 'movie camera'],
            ['char' => '📽️', 'name' => 'film projector'],
            ['char' => '📺', 'name' => 'television'],
            ['char' => '📻', 'name' => 'radio'],
            ['char' => '🎙️', 'name' => 'studio microphone'],
            ['char' => '📡', 'name' => 'satellite antenna'],
            ['char' => '🔋', 'name' => 'battery'],
            ['char' => '🔌', 'name' => 'electric plug'],
            ['char' => '💡', 'name' => 'light bulb'],
            ['char' => '🔦', 'name' => 'flashlight'],
            ['char' => '🕯️', 'name' => 'candle'],
            ['char' => '🧯', 'name' => 'fire extinguisher'],
            ['char' => '💸', 'name' => 'money with wings'],
            ['char' => '💵', 'name' => 'dollar banknote'],
            ['char' => '💴', 'name' => 'yen banknote'],
            ['char' => '💶', 'name' => 'euro banknote'],
            ['char' => '💷', 'name' => 'pound banknote'],
            ['char' => '💰', 'name' => 'money bag'],
            ['char' => '💳', 'name' => 'credit card'],
            ['char' => '💎', 'name' => 'gem stone'],
            ['char' => '⚖️', 'name' => 'balance scale'],
            ['char' => '🧰', 'name' => 'toolbox'],
            ['char' => '🔧', 'name' => 'wrench'],
            ['char' => '🔨', 'name' => 'hammer'],
            ['char' => '⚒️', 'name' => 'hammer and pick'],
            ['char' => '🛠️', 'name' => 'hammer and wrench'],
            ['char' => '⛏️', 'name' => 'pick'],
            ['char' => '🔩', 'name' => 'nut and bolt'],
            ['char' => '⚙️', 'name' => 'gear'],
            ['char' => '🧲', 'name' => 'magnet'],
            ['char' => '🔗', 'name' => 'link'],
            ['char' => '⛓️', 'name' => 'chains'],
            ['char' => '🧪', 'name' => 'test tube'],
            ['char' => '🧫', 'name' => 'petri dish'],
            ['char' => '🧬', 'name' => 'dna'],
            ['char' => '🔬', 'name' => 'microscope'],
            ['char' => '🔭', 'name' => 'telescope'],
            ['char' => '📡', 'name' => 'satellite antenna'],
            ['char' => '💉', 'name' => 'syringe'],
            ['char' => '🩸', 'name' => 'drop of blood'],
            ['char' => '💊', 'name' => 'pill'],
            ['char' => '🩹', 'name' => 'adhesive bandage'],
            ['char' => '🩺', 'name' => 'stethoscope'],
            ['char' => '🚪', 'name' => 'door'],
            ['char' => '🛏️', 'name' => 'bed'],
            ['char' => '🛋️', 'name' => 'couch and lamp'],
            ['char' => '🪑', 'name' => 'chair'],
            ['char' => '🚽', 'name' => 'toilet'],
            ['char' => '🚿', 'name' => 'shower'],
            ['char' => '🛁', 'name' => 'bathtub'],
            ['char' => '🪒', 'name' => 'razor'],
            ['char' => '🧴', 'name' => 'lotion bottle'],
            ['char' => '🧷', 'name' => 'safety pin'],
            ['char' => '🧹', 'name' => 'broom'],
            ['char' => '🧺', 'name' => 'basket'],
            ['char' => '🧻', 'name' => 'roll of paper'],
            ['char' => '🧼', 'name' => 'soap'],
            ['char' => '🧽', 'name' => 'sponge'],
            ['char' => '🔑', 'name' => 'key'],
            ['char' => '🗝️', 'name' => 'old key'],
            ['char' => '🔐', 'name' => 'locked with key'],
            ['char' => '🔒', 'name' => 'locked'],
            ['char' => '🔓', 'name' => 'unlocked'],
            ['char' => '📦', 'name' => 'package'],
            ['char' => '📫', 'name' => 'closed mailbox with raised flag'],
            ['char' => '📪', 'name' => 'closed mailbox with lowered flag'],
            ['char' => '📬', 'name' => 'open mailbox with raised flag'],
            ['char' => '📭', 'name' => 'open mailbox with lowered flag'],
            ['char' => '📮', 'name' => 'postbox'],
            ['char' => '✏️', 'name' => 'pencil'],
            ['char' => '✒️', 'name' => 'black nib'],
            ['char' => '🖋️', 'name' => 'fountain pen'],
            ['char' => '🖊️', 'name' => 'pen'],
            ['char' => '🖌️', 'name' => 'paintbrush'],
            ['char' => '🖍️', 'name' => 'crayon'],
            ['char' => '📝', 'name' => 'memo'],
            ['char' => '📁', 'name' => 'file folder'],
            ['char' => '📂', 'name' => 'open file folder'],
            ['char' => '📅', 'name' => 'calendar'],
            ['char' => '📆', 'name' => 'tear-off calendar'],
            ['char' => '📇', 'name' => 'card index'],
            ['char' => '📈', 'name' => 'chart increasing'],
            ['char' => '📉', 'name' => 'chart decreasing'],
            ['char' => '📊', 'name' => 'bar chart'],
            ['char' => '📋', 'name' => 'clipboard'],
            ['char' => '📌', 'name' => 'pushpin'],
            ['char' => '📍', 'name' => 'round pushpin'],
            ['char' => '📎', 'name' => 'paperclip'],
            ['char' => '🖇️', 'name' => 'linked paperclips'],
            ['char' => '📏', 'name' => 'straight ruler'],
            ['char' => '📐', 'name' => 'triangular ruler'],
            ['char' => '✂️', 'name' => 'scissors'],
            ['char' => '📕', 'name' => 'closed book'],
            ['char' => '📖', 'name' => 'open book'],
            ['char' => '📗', 'name' => 'green book'],
            ['char' => '📘', 'name' => 'blue book'],
            ['char' => '📙', 'name' => 'orange book'],
            ['char' => '📚', 'name' => 'books'],
            ['char' => '📓', 'name' => 'notebook'],
            ['char' => '📒', 'name' => 'ledger'],
            ['char' => '📃', 'name' => 'page with curl'],
            ['char' => '📜', 'name' => 'scroll'],
            ['char' => '📄', 'name' => 'page facing up'],
            ['char' => '📰', 'name' => 'newspaper'],
            ['char' => '🗞️', 'name' => 'rolled-up newspaper'],
            ['char' => '📑', 'name' => 'bookmark tabs'],
            ['char' => '🔖', 'name' => 'bookmark'],
            ['char' => '🏷️', 'name' => 'label'],
        ];
    }

    protected static function symbols(): array
    {
        return [
            // Hearts
            ['char' => '❤️', 'name' => 'red heart'],
            ['char' => '🧡', 'name' => 'orange heart'],
            ['char' => '💛', 'name' => 'yellow heart'],
            ['char' => '💚', 'name' => 'green heart'],
            ['char' => '💙', 'name' => 'blue heart'],
            ['char' => '💜', 'name' => 'purple heart'],
            ['char' => '🖤', 'name' => 'black heart'],
            ['char' => '🤍', 'name' => 'white heart'],
            ['char' => '🤎', 'name' => 'brown heart'],
            ['char' => '💔', 'name' => 'broken heart'],
            ['char' => '❣️', 'name' => 'heart exclamation'],
            ['char' => '💕', 'name' => 'two hearts'],
            ['char' => '💞', 'name' => 'revolving hearts'],
            ['char' => '💓', 'name' => 'beating heart'],
            ['char' => '💗', 'name' => 'growing heart'],
            ['char' => '💖', 'name' => 'sparkling heart'],
            ['char' => '💘', 'name' => 'heart with arrow'],
            ['char' => '💝', 'name' => 'heart with ribbon'],
            ['char' => '💟', 'name' => 'heart decoration'],
            // Money symbols
            ['char' => '💰', 'name' => 'money bag'],
            ['char' => '💱', 'name' => 'currency exchange'],
            ['char' => '💲', 'name' => 'heavy dollar sign'],
            ['char' => '💳', 'name' => 'credit card'],
            ['char' => '💴', 'name' => 'yen banknote'],
            ['char' => '💵', 'name' => 'dollar banknote'],
            ['char' => '💶', 'name' => 'euro banknote'],
            ['char' => '💷', 'name' => 'pound banknote'],
            ['char' => '💸', 'name' => 'money with wings'],
            ['char' => '💹', 'name' => 'chart increasing with yen'],
            // Religious symbols
            ['char' => '☮️', 'name' => 'peace symbol'],
            ['char' => '✝️', 'name' => 'latin cross'],
            ['char' => '☪️', 'name' => 'star and crescent'],
            ['char' => '🕉️', 'name' => 'om'],
            ['char' => '☸️', 'name' => 'wheel of dharma'],
            ['char' => '✡️', 'name' => 'star of david'],
            ['char' => '🔯', 'name' => 'dotted six-pointed star'],
            ['char' => '🕎', 'name' => 'menorah'],
            ['char' => '☯️', 'name' => 'yin yang'],
            ['char' => '☦️', 'name' => 'orthodox cross'],
            ['char' => '🛐', 'name' => 'place of worship'],
            ['char' => '⛪', 'name' => 'church'],
            ['char' => '🕋', 'name' => 'kaaba'],
            ['char' => '🕌', 'name' => 'mosque'],
            ['char' => '🕍', 'name' => 'synagogue'],
            ['char' => '🛕', 'name' => 'hindu temple'],
            ['char' => '📿', 'name' => 'prayer beads'],
            // Zodiac
            ['char' => '⛎', 'name' => 'ophiuchus'],
            ['char' => '♈', 'name' => 'aries'],
            ['char' => '♉', 'name' => 'taurus'],
            ['char' => '♊', 'name' => 'gemini'],
            ['char' => '♋', 'name' => 'cancer'],
            ['char' => '♌', 'name' => 'leo'],
            ['char' => '♍', 'name' => 'virgo'],
            ['char' => '♎', 'name' => 'libra'],
            ['char' => '♏', 'name' => 'scorpio'],
            ['char' => '♐', 'name' => 'sagittarius'],
            ['char' => '♑', 'name' => 'capricorn'],
            ['char' => '♒', 'name' => 'aquarius'],
            ['char' => '♓', 'name' => 'pisces'],
            // Alphanumeric symbols
            ['char' => '🔟', 'name' => 'keycap ten'],
            ['char' => '🔠', 'name' => 'input latin uppercase'],
            ['char' => '🔡', 'name' => 'input latin lowercase'],
            ['char' => '🔢', 'name' => 'input numbers'],
            ['char' => '🔣', 'name' => 'input symbols'],
            ['char' => '🔤', 'name' => 'input latin letters'],
            ['char' => '🆔', 'name' => 'id button'],
            ['char' => '🆚', 'name' => 'vs button'],
            ['char' => '🅰️', 'name' => 'A button'],
            ['char' => '🅱️', 'name' => 'B button'],
            ['char' => '🆎', 'name' => 'AB button'],
            ['char' => '🆑', 'name' => 'CL button'],
            ['char' => '🅾️', 'name' => 'O button'],
            ['char' => '🆘', 'name' => 'SOS button'],
            // Warning and hazard
            ['char' => '⚛️', 'name' => 'atom symbol'],
            ['char' => '☢️', 'name' => 'radioactive'],
            ['char' => '☣️', 'name' => 'biohazard'],
            ['char' => '⚠️', 'name' => 'warning'],
            ['char' => '🔞', 'name' => 'no one under eighteen'],
            ['char' => '📵', 'name' => 'no mobile phones'],
            ['char' => '🚫', 'name' => 'prohibited'],
            ['char' => '⛔', 'name' => 'no entry'],
            ['char' => '🛑', 'name' => 'stop sign'],
            ['char' => '🚷', 'name' => 'no pedestrians'],
            ['char' => '🚯', 'name' => 'no littering'],
            ['char' => '🚳', 'name' => 'no bicycles'],
            ['char' => '🚱', 'name' => 'non-potable water'],
            // Misc symbols
            ['char' => '💯', 'name' => 'hundred points'],
            ['char' => '💢', 'name' => 'anger symbol'],
            ['char' => '💥', 'name' => 'collision'],
            ['char' => '💦', 'name' => 'sweat droplets'],
            ['char' => '💨', 'name' => 'dashing away'],
            ['char' => '💠', 'name' => 'diamond with a dot'],
            ['char' => '💮', 'name' => 'white flower'],
            ['char' => '♨️', 'name' => 'hot springs'],
            ['char' => '🔥', 'name' => 'fire'],
            ['char' => '✨', 'name' => 'sparkles'],
            ['char' => '⭐', 'name' => 'star'],
            ['char' => '🌟', 'name' => 'glowing star'],
            ['char' => '✴️', 'name' => 'eight-pointed star'],
            ['char' => '🔔', 'name' => 'bell'],
            ['char' => '🔕', 'name' => 'bell with slash'],
            ['char' => '🎵', 'name' => 'musical note'],
            ['char' => '🎶', 'name' => 'musical notes'],
            ['char' => '📴', 'name' => 'mobile phone off'],
            ['char' => '📳', 'name' => 'vibration mode'],
            // Check marks and crosses
            ['char' => '✅', 'name' => 'check mark button'],
            ['char' => '☑️', 'name' => 'check box with check'],
            ['char' => '✔️', 'name' => 'check mark'],
            ['char' => '❌', 'name' => 'cross mark'],
            ['char' => '❎', 'name' => 'cross mark button'],
            ['char' => '⭕', 'name' => 'hollow red circle'],
            // Arrows
            ['char' => '🔃', 'name' => 'clockwise vertical arrows'],
            ['char' => '🔄', 'name' => 'counterclockwise arrows button'],
            ['char' => '🔙', 'name' => 'back arrow'],
            ['char' => '🔚', 'name' => 'end arrow'],
            ['char' => '🔛', 'name' => 'on arrow'],
            ['char' => '🔜', 'name' => 'soon arrow'],
            ['char' => '🔝', 'name' => 'top arrow'],
            ['char' => '⬆️', 'name' => 'up arrow'],
            ['char' => '⬇️', 'name' => 'down arrow'],
            ['char' => '⬅️', 'name' => 'left arrow'],
            ['char' => '➡️', 'name' => 'right arrow'],
            ['char' => '↗️', 'name' => 'up-right arrow'],
            ['char' => '↘️', 'name' => 'down-right arrow'],
            ['char' => '↙️', 'name' => 'down-left arrow'],
            ['char' => '↖️', 'name' => 'up-left arrow'],
            ['char' => '↕️', 'name' => 'up-down arrow'],
            ['char' => '↔️', 'name' => 'left-right arrow'],
            // Geometric shapes
            ['char' => '🔴', 'name' => 'red circle'],
            ['char' => '🟠', 'name' => 'orange circle'],
            ['char' => '🟡', 'name' => 'yellow circle'],
            ['char' => '🟢', 'name' => 'green circle'],
            ['char' => '🔵', 'name' => 'blue circle'],
            ['char' => '🟣', 'name' => 'purple circle'],
            ['char' => '🟤', 'name' => 'brown circle'],
            ['char' => '⚫', 'name' => 'black circle'],
            ['char' => '⚪', 'name' => 'white circle'],
            ['char' => '🔘', 'name' => 'radio button'],
            ['char' => '🟥', 'name' => 'red square'],
            ['char' => '🟧', 'name' => 'orange square'],
            ['char' => '🟨', 'name' => 'yellow square'],
            ['char' => '🟩', 'name' => 'green square'],
            ['char' => '🟦', 'name' => 'blue square'],
            ['char' => '🟪', 'name' => 'purple square'],
            ['char' => '🟫', 'name' => 'brown square'],
            ['char' => '⬛', 'name' => 'black large square'],
            ['char' => '⬜', 'name' => 'white large square'],
            ['char' => '◼️', 'name' => 'black medium square'],
            ['char' => '◻️', 'name' => 'white medium square'],
            ['char' => '◾', 'name' => 'black medium-small square'],
            ['char' => '◽', 'name' => 'white medium-small square'],
            ['char' => '▪️', 'name' => 'black small square'],
            ['char' => '▫️', 'name' => 'white small square'],
            ['char' => '🔶', 'name' => 'large orange diamond'],
            ['char' => '🔷', 'name' => 'large blue diamond'],
            ['char' => '🔸', 'name' => 'small orange diamond'],
            ['char' => '🔹', 'name' => 'small blue diamond'],
            ['char' => '🔺', 'name' => 'red triangle pointed up'],
            ['char' => '🔻', 'name' => 'red triangle pointed down'],
            ['char' => '🔲', 'name' => 'black square button'],
            ['char' => '🔳', 'name' => 'white square button'],
            // Japanese buttons
            ['char' => '🈶', 'name' => 'Japanese not free of charge button'],
            ['char' => '🈚', 'name' => 'Japanese free of charge button'],
            ['char' => '🈸', 'name' => 'Japanese application button'],
            ['char' => '🈺', 'name' => 'Japanese open for business button'],
            ['char' => '🈷️', 'name' => 'Japanese monthly amount button'],
            ['char' => '🉑', 'name' => 'Japanese acceptable button'],
            ['char' => '🉐', 'name' => 'Japanese bargain button'],
            ['char' => '㊙️', 'name' => 'Japanese secret button'],
            ['char' => '㊗️', 'name' => 'Japanese congratulations button'],
            ['char' => '🈴', 'name' => 'Japanese passing grade button'],
            ['char' => '🈵', 'name' => 'Japanese no vacancy button'],
            ['char' => '🈹', 'name' => 'Japanese discount button'],
            ['char' => '🈲', 'name' => 'Japanese prohibited button'],
            // Misc
            ['char' => '📛', 'name' => 'name badge'],
            ['char' => '🔰', 'name' => 'Japanese symbol for beginner'],
            ['char' => '🔱', 'name' => 'trident emblem'],
            ['char' => '⚜️', 'name' => 'fleur-de-lis'],
            ['char' => '🧿', 'name' => 'nazar amulet'],
            ['char' => '♾️', 'name' => 'infinity'],
            ['char' => '©️', 'name' => 'copyright'],
            ['char' => '®️', 'name' => 'registered'],
            ['char' => '™️', 'name' => 'trade mark'],
        ];
    }

    protected static function flags(): array
    {
        return [
            ['char' => '🏳️', 'name' => 'white flag'],
            ['char' => '🏴', 'name' => 'black flag'],
            ['char' => '🏁', 'name' => 'chequered flag'],
            ['char' => '🚩', 'name' => 'triangular flag'],
            ['char' => '🏳️‍🌈', 'name' => 'rainbow flag'],
            ['char' => '🏳️‍⚧️', 'name' => 'transgender flag'],
            ['char' => '🇺🇸', 'name' => 'United States'],
            ['char' => '🇬🇧', 'name' => 'United Kingdom'],
            ['char' => '🇨🇦', 'name' => 'Canada'],
            ['char' => '🇦🇺', 'name' => 'Australia'],
            ['char' => '🇩🇪', 'name' => 'Germany'],
            ['char' => '🇫🇷', 'name' => 'France'],
            ['char' => '🇮🇹', 'name' => 'Italy'],
            ['char' => '🇪🇸', 'name' => 'Spain'],
            ['char' => '🇯🇵', 'name' => 'Japan'],
            ['char' => '🇰🇷', 'name' => 'South Korea'],
            ['char' => '🇨🇳', 'name' => 'China'],
            ['char' => '🇮🇳', 'name' => 'India'],
            ['char' => '🇧🇷', 'name' => 'Brazil'],
            ['char' => '🇲🇽', 'name' => 'Mexico'],
            ['char' => '🇷🇺', 'name' => 'Russia'],
            ['char' => '🇿🇦', 'name' => 'South Africa'],
            ['char' => '🇳🇱', 'name' => 'Netherlands'],
            ['char' => '🇧🇪', 'name' => 'Belgium'],
            ['char' => '🇨🇭', 'name' => 'Switzerland'],
            ['char' => '🇦🇹', 'name' => 'Austria'],
            ['char' => '🇸🇪', 'name' => 'Sweden'],
            ['char' => '🇳🇴', 'name' => 'Norway'],
            ['char' => '🇩🇰', 'name' => 'Denmark'],
            ['char' => '🇫🇮', 'name' => 'Finland'],
            ['char' => '🇵🇱', 'name' => 'Poland'],
            ['char' => '🇺🇦', 'name' => 'Ukraine'],
            ['char' => '🇹🇷', 'name' => 'Turkey'],
            ['char' => '🇬🇷', 'name' => 'Greece'],
            ['char' => '🇵🇹', 'name' => 'Portugal'],
            ['char' => '🇮🇪', 'name' => 'Ireland'],
            ['char' => '🇳🇿', 'name' => 'New Zealand'],
            ['char' => '🇸🇬', 'name' => 'Singapore'],
            ['char' => '🇭🇰', 'name' => 'Hong Kong'],
            ['char' => '🇹🇼', 'name' => 'Taiwan'],
            ['char' => '🇹🇭', 'name' => 'Thailand'],
            ['char' => '🇻🇳', 'name' => 'Vietnam'],
            ['char' => '🇮🇩', 'name' => 'Indonesia'],
            ['char' => '🇵🇭', 'name' => 'Philippines'],
            ['char' => '🇲🇾', 'name' => 'Malaysia'],
            ['char' => '🇦🇷', 'name' => 'Argentina'],
            ['char' => '🇨🇴', 'name' => 'Colombia'],
            ['char' => '🇨🇱', 'name' => 'Chile'],
            ['char' => '🇵🇪', 'name' => 'Peru'],
            ['char' => '🇪🇬', 'name' => 'Egypt'],
            ['char' => '🇸🇦', 'name' => 'Saudi Arabia'],
            ['char' => '🇦🇪', 'name' => 'United Arab Emirates'],
            ['char' => '🇮🇱', 'name' => 'Israel'],
        ];
    }
}
